sudo: required
services:
  - docker

before_install:
  - docker build -t mictat/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true mictat/docker-react-test npm run test -- --coverage
